# Generated by Django 6.0.6 on 2026-07-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "verbose_name": "Commentary",
                "verbose_name_plural": "Commentaries",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_time"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="owner",
            new_name="user",
        ),
    ]
